# Generated by Django 4.2.1 on 2023-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnaem', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.IntegerField(max_length=14)),
                ('password', models.CharField(max_length=4)),
            ],
        ),
    ]
