# Generated by Django 4.2.1 on 2023-05-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_category_food_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_item',
            old_name='categorry',
            new_name='category',
        ),
    ]
