# Generated by Django 4.2.1 on 2023-05-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_categorry_food_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_item',
            name='image',
            field=models.ImageField(default=None, upload_to='upload/Food_item/'),
        ),
    ]
