# Generated by Django 4.1.5 on 2023-06-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_food_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food_item",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
