# Generated by Django 4.1.5 on 2023-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=50)),
                ("customer", models.EmailField(max_length=254)),
                ("status", models.BooleanField(default=False)),
            ],
        ),
    ]
