# Generated by Django 4.2.1 on 2023-09-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
    ]
